### ISSUE TITLE
Transparent PNG Issues

### ISSUE THREAD

**Issue by candideu** [romadox/zine-arranger#1]
Thank you so so so so much for creating this tool!! I've just printed my first zine, and your tool was indispensable in making the print process efficient and effective.

I just wanted to report a minor bug I encountered with transparent PNGs, and didn't realize until after the print. It appears that the white backgrounds are added to transparent PNGs.

Here's an example with the cover of my zine:

Original PDF: https://github.com/pocket-portal/zine/blob/main/Pocket%20Portal%20Power%20Play%20(v1).pdf

Zine Arranger PDF: https://github.com/pocket-portal/zine/blob/main/Pocket%20Portal%20Power%20Play%20-%20Quarter%20Print%20(v1).pdf

Source code with images: https://github.com/pocket-portal/zine

**Comment by romadox** [comment]
Oh no! That's no good.

I just tested your original out on Firefox on Linux Mint & the transparent PNGs came out okay, even on the saved version. That makes me suspect it has to do with the print function of the browser. (What browser / OS were you using, if you don't mind sharing?)

Unfortunately if it's related to the browser's print function, I think the only way to properly fix this would be to have Zine Arranger actually render the printable PDF within the JavaScript itself, so we aren't relying on the browser to 'print' it. That might be possible, but it isn't something I know how to do!

Alternately, if you have a second browser to try, you may have better luck with that. Also since it's working for me, I can render one to send to you if needed! It looks like the original PDF you linked doesn't have pages spaced out for printing, so if you have the version you used to render your printable copy, I can run that through!

**Comment by candideu** [comment]
So, I just re-tested it on Firefox on Windows 10, and the problem seemed to have solved itself? Same browser I used initially, but now it's all good.

Here's the corrected version:

https://github.com/pocket-portal/zine/blob/main/Pocket%20Portal%20Power%20Play%20-%20print-ready%20-%20(v1).pdf

I'm not sure what I did differently, but I'm glad the PNGs appear correctly now. I'll probably do another test print to see how that goes, but I'll close this issue. Thank you for your assistance!
